name: tests workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-matrix:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            zig-arch: "x86_64-linux"
          - os: macos-latest
            zig-arch: "aarch64-macos"
    name: test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./.github/actions/prepare-build
        with:
          zig-arch: ${{ matrix.zig-arch }}

      - run: uv run alias build
      - run: uv run alias test

  verify-matrix:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [test-matrix]
    steps:
      - run: exit 1
        if: ${{ contains(toJSON(needs.*.result), 'failure') || contains(toJSON(needs.*.result), 'cancelled') }}
